/**
 * Catalog of every real PNG under public/assets/statling/characters/deco —
 * generated from a one-off filesystem + PNG-header probe, never guessed.
 *
 * None of these 240 items are wired into any screen yet, and their filenames
 * (accessory_NNN.png, plain sequence numbers) carry no recoverable slot information —
 * so every item is cataloged under slot 'unknown' rather than guessed. Reclassify an
 * item by (1) looking at the actual image, (2) moving its file from
 * characters/deco/unknown/ to characters/deco/{realSlot}/, (3) updating its 
 * `slot` here. See docs/asset-migration-map.md.
 */

/** 'eyes' was folded into 'face' — glasses/goggles/eyepatches etc. anchor there instead of getting their own slot. */
export type DecoSlot = 'head' | 'face' | 'neck' | 'body' | 'back' | 'hand' | 'effect' | 'unknown'

export interface CharacterDecoAssetDefinition {
  id: string
  displayName: string
  slot: DecoSlot
  src: string
  canvasSize: { width: number; height: number }
  anchor?: { x: number; y: number }
  scale?: number
}

const DECO_BASE = '/assets/statling/characters/deco'

export const CHARACTER_DECO_ASSETS: Record<string, CharacterDecoAssetDefinition> = {
  'accessory_001': { id: 'accessory_001', displayName: 'accessory_001', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_001.png`, canvasSize: { width: 169, height: 123 } },
  'accessory_002': { id: 'accessory_002', displayName: 'accessory_002', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_002.png`, canvasSize: { width: 149, height: 146 } },
  'accessory_003': { id: 'accessory_003', displayName: 'accessory_003', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_003.png`, canvasSize: { width: 180, height: 129 } },
  'accessory_004': { id: 'accessory_004', displayName: 'accessory_004', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_004.png`, canvasSize: { width: 159, height: 131 } },
  'accessory_005': { id: 'accessory_005', displayName: 'accessory_005', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_005.png`, canvasSize: { width: 155, height: 128 } },
  'accessory_006': { id: 'accessory_006', displayName: 'accessory_006', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_006.png`, canvasSize: { width: 159, height: 133 } },
  'accessory_007': { id: 'accessory_007', displayName: 'accessory_007', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_007.png`, canvasSize: { width: 148, height: 129 } },
  'accessory_008': { id: 'accessory_008', displayName: 'accessory_008', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_008.png`, canvasSize: { width: 175, height: 136 } },
  'accessory_009': { id: 'accessory_009', displayName: 'accessory_009', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_009.png`, canvasSize: { width: 154, height: 156 } },
  'accessory_010': { id: 'accessory_010', displayName: 'accessory_010', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_010.png`, canvasSize: { width: 153, height: 148 } },
  'accessory_011': { id: 'accessory_011', displayName: 'accessory_011', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_011.png`, canvasSize: { width: 142, height: 151 } },
  'accessory_012': { id: 'accessory_012', displayName: 'accessory_012', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_012.png`, canvasSize: { width: 163, height: 140 } },
  'accessory_013': { id: 'accessory_013', displayName: 'accessory_013', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_013.png`, canvasSize: { width: 140, height: 128 } },
  'accessory_014': { id: 'accessory_014', displayName: 'accessory_014', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_014.png`, canvasSize: { width: 167, height: 118 } },
  'accessory_015': { id: 'accessory_015', displayName: 'accessory_015', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_015.png`, canvasSize: { width: 171, height: 110 } },
  'accessory_016': { id: 'accessory_016', displayName: 'accessory_016', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_016.png`, canvasSize: { width: 122, height: 149 } },
  'accessory_017': { id: 'accessory_017', displayName: 'accessory_017', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_017.png`, canvasSize: { width: 169, height: 272 } },
  'accessory_018': { id: 'accessory_018', displayName: 'accessory_018', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_018.png`, canvasSize: { width: 164, height: 267 } },
  'accessory_019': { id: 'accessory_019', displayName: 'accessory_019', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_019.png`, canvasSize: { width: 164, height: 262 } },
  'accessory_020': { id: 'accessory_020', displayName: 'accessory_020', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_020.png`, canvasSize: { width: 137, height: 261 } },
  'accessory_021': { id: 'accessory_021', displayName: 'accessory_021', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_021.png`, canvasSize: { width: 159, height: 250 } },
  'accessory_022': { id: 'accessory_022', displayName: 'accessory_022', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_022.png`, canvasSize: { width: 171, height: 257 } },
  'accessory_023': { id: 'accessory_023', displayName: 'accessory_023', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_023.png`, canvasSize: { width: 164, height: 252 } },
  'accessory_024': { id: 'accessory_024', displayName: 'accessory_024', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_024.png`, canvasSize: { width: 157, height: 136 } },
  'accessory_025': { id: 'accessory_025', displayName: 'accessory_025', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_025.png`, canvasSize: { width: 147, height: 138 } },
  'accessory_026': { id: 'accessory_026', displayName: 'accessory_026', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_026.png`, canvasSize: { width: 143, height: 150 } },
  'accessory_027': { id: 'accessory_027', displayName: 'accessory_027', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_027.png`, canvasSize: { width: 143, height: 142 } },
  'accessory_028': { id: 'accessory_028', displayName: 'accessory_028', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_028.png`, canvasSize: { width: 140, height: 128 } },
  'accessory_029': { id: 'accessory_029', displayName: 'accessory_029', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_029.png`, canvasSize: { width: 133, height: 148 } },
  'accessory_030': { id: 'accessory_030', displayName: 'accessory_030', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_030.png`, canvasSize: { width: 123, height: 148 } },
  'accessory_031': { id: 'accessory_031', displayName: 'accessory_031', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_031.png`, canvasSize: { width: 115, height: 143 } },
  'accessory_032': { id: 'accessory_032', displayName: 'accessory_032', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_032.png`, canvasSize: { width: 113, height: 155 } },
  'accessory_033': { id: 'accessory_033', displayName: 'accessory_033', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_033.png`, canvasSize: { width: 144, height: 140 } },
  'accessory_034': { id: 'accessory_034', displayName: 'accessory_034', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_034.png`, canvasSize: { width: 149, height: 146 } },
  'accessory_035': { id: 'accessory_035', displayName: 'accessory_035', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_035.png`, canvasSize: { width: 116, height: 145 } },
  'accessory_036': { id: 'accessory_036', displayName: 'accessory_036', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_036.png`, canvasSize: { width: 121, height: 143 } },
  'accessory_037': { id: 'accessory_037', displayName: 'accessory_037', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_037.png`, canvasSize: { width: 116, height: 143 } },
  'accessory_038': { id: 'accessory_038', displayName: 'accessory_038', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_038.png`, canvasSize: { width: 106, height: 144 } },
  'accessory_039': { id: 'accessory_039', displayName: 'accessory_039', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_039.png`, canvasSize: { width: 130, height: 121 } },
  'accessory_040': { id: 'accessory_040', displayName: 'accessory_040', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_040.png`, canvasSize: { width: 135, height: 126 } },
  'accessory_041': { id: 'accessory_041', displayName: 'accessory_041', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_041.png`, canvasSize: { width: 160, height: 119 } },
  'accessory_042': { id: 'accessory_042', displayName: 'accessory_042', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_042.png`, canvasSize: { width: 165, height: 132 } },
  'accessory_043': { id: 'accessory_043', displayName: 'accessory_043', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_043.png`, canvasSize: { width: 167, height: 145 } },
  'accessory_044': { id: 'accessory_044', displayName: 'accessory_044', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_044.png`, canvasSize: { width: 180, height: 127 } },
  'accessory_045': { id: 'accessory_045', displayName: 'accessory_045', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_045.png`, canvasSize: { width: 168, height: 145 } },
  'accessory_046': { id: 'accessory_046', displayName: 'accessory_046', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_046.png`, canvasSize: { width: 174, height: 136 } },
  'accessory_047': { id: 'accessory_047', displayName: 'accessory_047', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_047.png`, canvasSize: { width: 164, height: 122 } },
  'accessory_048': { id: 'accessory_048', displayName: 'accessory_048', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_048.png`, canvasSize: { width: 162, height: 135 } },
  'accessory_049': { id: 'accessory_049', displayName: 'accessory_049', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_049.png`, canvasSize: { width: 160, height: 154 } },
  'accessory_050': { id: 'accessory_050', displayName: 'accessory_050', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_050.png`, canvasSize: { width: 162, height: 126 } },
  'accessory_051': { id: 'accessory_051', displayName: 'accessory_051', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_051.png`, canvasSize: { width: 146, height: 152 } },
  'accessory_052': { id: 'accessory_052', displayName: 'accessory_052', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_052.png`, canvasSize: { width: 174, height: 145 } },
  'accessory_053': { id: 'accessory_053', displayName: 'accessory_053', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_053.png`, canvasSize: { width: 162, height: 118 } },
  'accessory_054': { id: 'accessory_054', displayName: 'accessory_054', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_054.png`, canvasSize: { width: 137, height: 134 } },
  'accessory_055': { id: 'accessory_055', displayName: 'accessory_055', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_055.png`, canvasSize: { width: 145, height: 126 } },
  'accessory_056': { id: 'accessory_056', displayName: 'accessory_056', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_056.png`, canvasSize: { width: 148, height: 138 } },
  'accessory_057': { id: 'accessory_057', displayName: 'accessory_057', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_057.png`, canvasSize: { width: 171, height: 247 } },
  'accessory_058': { id: 'accessory_058', displayName: 'accessory_058', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_058.png`, canvasSize: { width: 171, height: 250 } },
  'accessory_059': { id: 'accessory_059', displayName: 'accessory_059', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_059.png`, canvasSize: { width: 171, height: 252 } },
  'accessory_060': { id: 'accessory_060', displayName: 'accessory_060', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_060.png`, canvasSize: { width: 146, height: 262 } },
  'accessory_061': { id: 'accessory_061', displayName: 'accessory_061', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_061.png`, canvasSize: { width: 163, height: 272 } },
  'accessory_062': { id: 'accessory_062', displayName: 'accessory_062', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_062.png`, canvasSize: { width: 163, height: 268 } },
  'accessory_063': { id: 'accessory_063', displayName: 'accessory_063', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_063.png`, canvasSize: { width: 170, height: 268 } },
  'accessory_064': { id: 'accessory_064', displayName: 'accessory_064', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_064.png`, canvasSize: { width: 158, height: 96 } },
  'accessory_065': { id: 'accessory_065', displayName: 'accessory_065', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_065.png`, canvasSize: { width: 154, height: 145 } },
  'accessory_066': { id: 'accessory_066', displayName: 'accessory_066', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_066.png`, canvasSize: { width: 158, height: 146 } },
  'accessory_067': { id: 'accessory_067', displayName: 'accessory_067', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_067.png`, canvasSize: { width: 160, height: 129 } },
  'accessory_068': { id: 'accessory_068', displayName: 'accessory_068', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_068.png`, canvasSize: { width: 154, height: 149 } },
  'accessory_069': { id: 'accessory_069', displayName: 'accessory_069', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_069.png`, canvasSize: { width: 133, height: 149 } },
  'accessory_070': { id: 'accessory_070', displayName: 'accessory_070', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_070.png`, canvasSize: { width: 126, height: 128 } },
  'accessory_071': { id: 'accessory_071', displayName: 'accessory_071', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_071.png`, canvasSize: { width: 116, height: 133 } },
  'accessory_072': { id: 'accessory_072', displayName: 'accessory_072', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_072.png`, canvasSize: { width: 170, height: 284 } },
  'accessory_073': { id: 'accessory_073', displayName: 'accessory_073', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_073.png`, canvasSize: { width: 148, height: 134 } },
  'accessory_074': { id: 'accessory_074', displayName: 'accessory_074', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_074.png`, canvasSize: { width: 146, height: 137 } },
  'accessory_075': { id: 'accessory_075', displayName: 'accessory_075', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_075.png`, canvasSize: { width: 118, height: 147 } },
  'accessory_076': { id: 'accessory_076', displayName: 'accessory_076', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_076.png`, canvasSize: { width: 120, height: 144 } },
  'accessory_077': { id: 'accessory_077', displayName: 'accessory_077', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_077.png`, canvasSize: { width: 120, height: 144 } },
  'accessory_078': { id: 'accessory_078', displayName: 'accessory_078', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_078.png`, canvasSize: { width: 116, height: 144 } },
  'accessory_079': { id: 'accessory_079', displayName: 'accessory_079', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_079.png`, canvasSize: { width: 133, height: 130 } },
  'accessory_080': { id: 'accessory_080', displayName: 'accessory_080', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_080.png`, canvasSize: { width: 137, height: 146 } },
  'accessory_081': { id: 'accessory_081', displayName: 'accessory_081', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_081.png`, canvasSize: { width: 164, height: 123 } },
  'accessory_082': { id: 'accessory_082', displayName: 'accessory_082', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_082.png`, canvasSize: { width: 163, height: 132 } },
  'accessory_083': { id: 'accessory_083', displayName: 'accessory_083', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_083.png`, canvasSize: { width: 165, height: 146 } },
  'accessory_084': { id: 'accessory_084', displayName: 'accessory_084', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_084.png`, canvasSize: { width: 176, height: 126 } },
  'accessory_085': { id: 'accessory_085', displayName: 'accessory_085', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_085.png`, canvasSize: { width: 163, height: 139 } },
  'accessory_086': { id: 'accessory_086', displayName: 'accessory_086', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_086.png`, canvasSize: { width: 170, height: 139 } },
  'accessory_087': { id: 'accessory_087', displayName: 'accessory_087', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_087.png`, canvasSize: { width: 159, height: 126 } },
  'accessory_088': { id: 'accessory_088', displayName: 'accessory_088', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_088.png`, canvasSize: { width: 159, height: 133 } },
  'accessory_089': { id: 'accessory_089', displayName: 'accessory_089', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_089.png`, canvasSize: { width: 154, height: 157 } },
  'accessory_090': { id: 'accessory_090', displayName: 'accessory_090', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_090.png`, canvasSize: { width: 160, height: 128 } },
  'accessory_091': { id: 'accessory_091', displayName: 'accessory_091', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_091.png`, canvasSize: { width: 141, height: 154 } },
  'accessory_092': { id: 'accessory_092', displayName: 'accessory_092', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_092.png`, canvasSize: { width: 165, height: 146 } },
  'accessory_093': { id: 'accessory_093', displayName: 'accessory_093', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_093.png`, canvasSize: { width: 155, height: 119 } },
  'accessory_094': { id: 'accessory_094', displayName: 'accessory_094', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_094.png`, canvasSize: { width: 134, height: 135 } },
  'accessory_095': { id: 'accessory_095', displayName: 'accessory_095', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_095.png`, canvasSize: { width: 140, height: 124 } },
  'accessory_096': { id: 'accessory_096', displayName: 'accessory_096', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_096.png`, canvasSize: { width: 150, height: 137 } },
  'accessory_097': { id: 'accessory_097', displayName: 'accessory_097', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_097.png`, canvasSize: { width: 171, height: 241 } },
  'accessory_098': { id: 'accessory_098', displayName: 'accessory_098', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_098.png`, canvasSize: { width: 169, height: 247 } },
  'accessory_099': { id: 'accessory_099', displayName: 'accessory_099', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_099.png`, canvasSize: { width: 170, height: 242 } },
  'accessory_100': { id: 'accessory_100', displayName: 'accessory_100', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_100.png`, canvasSize: { width: 141, height: 256 } },
  'accessory_101': { id: 'accessory_101', displayName: 'accessory_101', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_101.png`, canvasSize: { width: 164, height: 267 } },
  'accessory_102': { id: 'accessory_102', displayName: 'accessory_102', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_102.png`, canvasSize: { width: 169, height: 261 } },
  'accessory_103': { id: 'accessory_103', displayName: 'accessory_103', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_103.png`, canvasSize: { width: 171, height: 261 } },
  'accessory_104': { id: 'accessory_104', displayName: 'accessory_104', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_104.png`, canvasSize: { width: 183, height: 256 } },
  'accessory_105': { id: 'accessory_105', displayName: 'accessory_105', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_105.png`, canvasSize: { width: 155, height: 143 } },
  'accessory_106': { id: 'accessory_106', displayName: 'accessory_106', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_106.png`, canvasSize: { width: 158, height: 145 } },
  'accessory_107': { id: 'accessory_107', displayName: 'accessory_107', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_107.png`, canvasSize: { width: 161, height: 129 } },
  'accessory_108': { id: 'accessory_108', displayName: 'accessory_108', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_108.png`, canvasSize: { width: 154, height: 144 } },
  'accessory_109': { id: 'accessory_109', displayName: 'accessory_109', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_109.png`, canvasSize: { width: 130, height: 150 } },
  'accessory_110': { id: 'accessory_110', displayName: 'accessory_110', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_110.png`, canvasSize: { width: 125, height: 127 } },
  'accessory_111': { id: 'accessory_111', displayName: 'accessory_111', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_111.png`, canvasSize: { width: 119, height: 137 } },
  'accessory_112': { id: 'accessory_112', displayName: 'accessory_112', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_112.png`, canvasSize: { width: 110, height: 140 } },
  'accessory_113': { id: 'accessory_113', displayName: 'accessory_113', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_113.png`, canvasSize: { width: 148, height: 137 } },
  'accessory_114': { id: 'accessory_114', displayName: 'accessory_114', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_114.png`, canvasSize: { width: 146, height: 141 } },
  'accessory_115': { id: 'accessory_115', displayName: 'accessory_115', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_115.png`, canvasSize: { width: 118, height: 144 } },
  'accessory_116': { id: 'accessory_116', displayName: 'accessory_116', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_116.png`, canvasSize: { width: 121, height: 144 } },
  'accessory_117': { id: 'accessory_117', displayName: 'accessory_117', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_117.png`, canvasSize: { width: 120, height: 144 } },
  'accessory_118': { id: 'accessory_118', displayName: 'accessory_118', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_118.png`, canvasSize: { width: 114, height: 144 } },
  'accessory_119': { id: 'accessory_119', displayName: 'accessory_119', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_119.png`, canvasSize: { width: 133, height: 132 } },
  'accessory_120': { id: 'accessory_120', displayName: 'accessory_120', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_120.png`, canvasSize: { width: 128, height: 145 } },
  'accessory_121': { id: 'accessory_121', displayName: 'accessory_121', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_121.png`, canvasSize: { width: 171, height: 162 } },
  'accessory_122': { id: 'accessory_122', displayName: 'accessory_122', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_122.png`, canvasSize: { width: 180, height: 147 } },
  'accessory_123': { id: 'accessory_123', displayName: 'accessory_123', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_123.png`, canvasSize: { width: 147, height: 153 } },
  'accessory_124': { id: 'accessory_124', displayName: 'accessory_124', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_124.png`, canvasSize: { width: 232, height: 165 } },
  'accessory_125': { id: 'accessory_125', displayName: 'accessory_125', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_125.png`, canvasSize: { width: 151, height: 161 } },
  'accessory_126': { id: 'accessory_126', displayName: 'accessory_126', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_126.png`, canvasSize: { width: 162, height: 168 } },
  'accessory_127': { id: 'accessory_127', displayName: 'accessory_127', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_127.png`, canvasSize: { width: 117, height: 176 } },
  'accessory_128': { id: 'accessory_128', displayName: 'accessory_128', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_128.png`, canvasSize: { width: 163, height: 170 } },
  'accessory_129': { id: 'accessory_129', displayName: 'accessory_129', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_129.png`, canvasSize: { width: 146, height: 182 } },
  'accessory_130': { id: 'accessory_130', displayName: 'accessory_130', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_130.png`, canvasSize: { width: 150, height: 177 } },
  'accessory_131': { id: 'accessory_131', displayName: 'accessory_131', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_131.png`, canvasSize: { width: 133, height: 187 } },
  'accessory_132': { id: 'accessory_132', displayName: 'accessory_132', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_132.png`, canvasSize: { width: 143, height: 183 } },
  'accessory_133': { id: 'accessory_133', displayName: 'accessory_133', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_133.png`, canvasSize: { width: 168, height: 167 } },
  'accessory_134': { id: 'accessory_134', displayName: 'accessory_134', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_134.png`, canvasSize: { width: 155, height: 178 } },
  'accessory_135': { id: 'accessory_135', displayName: 'accessory_135', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_135.png`, canvasSize: { width: 127, height: 175 } },
  'accessory_136': { id: 'accessory_136', displayName: 'accessory_136', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_136.png`, canvasSize: { width: 141, height: 171 } },
  'accessory_137': { id: 'accessory_137', displayName: 'accessory_137', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_137.png`, canvasSize: { width: 174, height: 180 } },
  'accessory_138': { id: 'accessory_138', displayName: 'accessory_138', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_138.png`, canvasSize: { width: 167, height: 162 } },
  'accessory_139': { id: 'accessory_139', displayName: 'accessory_139', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_139.png`, canvasSize: { width: 177, height: 184 } },
  'accessory_140': { id: 'accessory_140', displayName: 'accessory_140', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_140.png`, canvasSize: { width: 142, height: 190 } },
  'accessory_141': { id: 'accessory_141', displayName: 'accessory_141', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_141.png`, canvasSize: { width: 179, height: 148 } },
  'accessory_142': { id: 'accessory_142', displayName: 'accessory_142', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_142.png`, canvasSize: { width: 164, height: 197 } },
  'accessory_143': { id: 'accessory_143', displayName: 'accessory_143', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_143.png`, canvasSize: { width: 178, height: 177 } },
  'accessory_144': { id: 'accessory_144', displayName: 'accessory_144', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_144.png`, canvasSize: { width: 156, height: 181 } },
  'accessory_145': { id: 'accessory_145', displayName: 'accessory_145', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_145.png`, canvasSize: { width: 148, height: 176 } },
  'accessory_146': { id: 'accessory_146', displayName: 'accessory_146', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_146.png`, canvasSize: { width: 144, height: 166 } },
  'accessory_147': { id: 'accessory_147', displayName: 'accessory_147', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_147.png`, canvasSize: { width: 173, height: 170 } },
  'accessory_148': { id: 'accessory_148', displayName: 'accessory_148', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_148.png`, canvasSize: { width: 139, height: 186 } },
  'accessory_149': { id: 'accessory_149', displayName: 'accessory_149', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_149.png`, canvasSize: { width: 144, height: 175 } },
  'accessory_150': { id: 'accessory_150', displayName: 'accessory_150', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_150.png`, canvasSize: { width: 167, height: 142 } },
  'accessory_151': { id: 'accessory_151', displayName: 'accessory_151', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_151.png`, canvasSize: { width: 168, height: 163 } },
  'accessory_152': { id: 'accessory_152', displayName: 'accessory_152', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_152.png`, canvasSize: { width: 162, height: 169 } },
  'accessory_153': { id: 'accessory_153', displayName: 'accessory_153', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_153.png`, canvasSize: { width: 178, height: 159 } },
  'accessory_154': { id: 'accessory_154', displayName: 'accessory_154', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_154.png`, canvasSize: { width: 153, height: 183 } },
  'accessory_155': { id: 'accessory_155', displayName: 'accessory_155', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_155.png`, canvasSize: { width: 154, height: 176 } },
  'accessory_156': { id: 'accessory_156', displayName: 'accessory_156', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_156.png`, canvasSize: { width: 155, height: 176 } },
  'accessory_157': { id: 'accessory_157', displayName: 'accessory_157', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_157.png`, canvasSize: { width: 149, height: 181 } },
  'accessory_158': { id: 'accessory_158', displayName: 'accessory_158', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_158.png`, canvasSize: { width: 180, height: 137 } },
  'accessory_159': { id: 'accessory_159', displayName: 'accessory_159', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_159.png`, canvasSize: { width: 149, height: 165 } },
  'accessory_160': { id: 'accessory_160', displayName: 'accessory_160', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_160.png`, canvasSize: { width: 172, height: 149 } },
  'accessory_161': { id: 'accessory_161', displayName: 'accessory_161', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_161.png`, canvasSize: { width: 132, height: 148 } },
  'accessory_162': { id: 'accessory_162', displayName: 'accessory_162', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_162.png`, canvasSize: { width: 154, height: 161 } },
  'accessory_163': { id: 'accessory_163', displayName: 'accessory_163', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_163.png`, canvasSize: { width: 167, height: 118 } },
  'accessory_164': { id: 'accessory_164', displayName: 'accessory_164', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_164.png`, canvasSize: { width: 143, height: 162 } },
  'accessory_165': { id: 'accessory_165', displayName: 'accessory_165', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_165.png`, canvasSize: { width: 170, height: 103 } },
  'accessory_166': { id: 'accessory_166', displayName: 'accessory_166', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_166.png`, canvasSize: { width: 138, height: 154 } },
  'accessory_167': { id: 'accessory_167', displayName: 'accessory_167', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_167.png`, canvasSize: { width: 167, height: 170 } },
  'accessory_168': { id: 'accessory_168', displayName: 'accessory_168', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_168.png`, canvasSize: { width: 142, height: 154 } },
  'accessory_169': { id: 'accessory_169', displayName: 'accessory_169', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_169.png`, canvasSize: { width: 125, height: 167 } },
  'accessory_170': { id: 'accessory_170', displayName: 'accessory_170', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_170.png`, canvasSize: { width: 163, height: 149 } },
  'accessory_171': { id: 'accessory_171', displayName: 'accessory_171', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_171.png`, canvasSize: { width: 125, height: 166 } },
  'accessory_172': { id: 'accessory_172', displayName: 'accessory_172', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_172.png`, canvasSize: { width: 132, height: 166 } },
  'accessory_173': { id: 'accessory_173', displayName: 'accessory_173', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_173.png`, canvasSize: { width: 107, height: 166 } },
  'accessory_174': { id: 'accessory_174', displayName: 'accessory_174', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_174.png`, canvasSize: { width: 152, height: 127 } },
  'accessory_175': { id: 'accessory_175', displayName: 'accessory_175', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_175.png`, canvasSize: { width: 157, height: 160 } },
  'accessory_176': { id: 'accessory_176', displayName: 'accessory_176', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_176.png`, canvasSize: { width: 121, height: 156 } },
  'accessory_177': { id: 'accessory_177', displayName: 'accessory_177', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_177.png`, canvasSize: { width: 160, height: 161 } },
  'accessory_178': { id: 'accessory_178', displayName: 'accessory_178', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_178.png`, canvasSize: { width: 107, height: 161 } },
  'accessory_179': { id: 'accessory_179', displayName: 'accessory_179', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_179.png`, canvasSize: { width: 143, height: 162 } },
  'accessory_180': { id: 'accessory_180', displayName: 'accessory_180', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_180.png`, canvasSize: { width: 134, height: 154 } },
  'accessory_181': { id: 'accessory_181', displayName: 'accessory_181', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_181.png`, canvasSize: { width: 168, height: 148 } },
  'accessory_182': { id: 'accessory_182', displayName: 'accessory_182', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_182.png`, canvasSize: { width: 130, height: 158 } },
  'accessory_183': { id: 'accessory_183', displayName: 'accessory_183', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_183.png`, canvasSize: { width: 139, height: 140 } },
  'accessory_184': { id: 'accessory_184', displayName: 'accessory_184', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_184.png`, canvasSize: { width: 129, height: 155 } },
  'accessory_185': { id: 'accessory_185', displayName: 'accessory_185', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_185.png`, canvasSize: { width: 155, height: 305 } },
  'accessory_186': { id: 'accessory_186', displayName: 'accessory_186', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_186.png`, canvasSize: { width: 146, height: 303 } },
  'accessory_187': { id: 'accessory_187', displayName: 'accessory_187', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_187.png`, canvasSize: { width: 139, height: 302 } },
  'accessory_188': { id: 'accessory_188', displayName: 'accessory_188', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_188.png`, canvasSize: { width: 145, height: 293 } },
  'accessory_189': { id: 'accessory_189', displayName: 'accessory_189', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_189.png`, canvasSize: { width: 177, height: 303 } },
  'accessory_190': { id: 'accessory_190', displayName: 'accessory_190', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_190.png`, canvasSize: { width: 154, height: 304 } },
  'accessory_191': { id: 'accessory_191', displayName: 'accessory_191', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_191.png`, canvasSize: { width: 168, height: 302 } },
  'accessory_192': { id: 'accessory_192', displayName: 'accessory_192', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_192.png`, canvasSize: { width: 136, height: 305 } },
  'accessory_193': { id: 'accessory_193', displayName: 'accessory_193', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_193.png`, canvasSize: { width: 134, height: 138 } },
  'accessory_194': { id: 'accessory_194', displayName: 'accessory_194', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_194.png`, canvasSize: { width: 113, height: 141 } },
  'accessory_195': { id: 'accessory_195', displayName: 'accessory_195', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_195.png`, canvasSize: { width: 186, height: 104 } },
  'accessory_196': { id: 'accessory_196', displayName: 'accessory_196', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_196.png`, canvasSize: { width: 119, height: 145 } },
  'accessory_197': { id: 'accessory_197', displayName: 'accessory_197', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_197.png`, canvasSize: { width: 132, height: 141 } },
  'accessory_198': { id: 'accessory_198', displayName: 'accessory_198', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_198.png`, canvasSize: { width: 152, height: 132 } },
  'accessory_199': { id: 'accessory_199', displayName: 'accessory_199', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_199.png`, canvasSize: { width: 127, height: 131 } },
  'accessory_200': { id: 'accessory_200', displayName: 'accessory_200', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_200.png`, canvasSize: { width: 122, height: 140 } },
  'accessory_201': { id: 'accessory_201', displayName: 'accessory_201', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_201.png`, canvasSize: { width: 114, height: 181 } },
  'accessory_202': { id: 'accessory_202', displayName: 'accessory_202', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_202.png`, canvasSize: { width: 166, height: 168 } },
  'accessory_203': { id: 'accessory_203', displayName: 'accessory_203', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_203.png`, canvasSize: { width: 193, height: 109 } },
  'accessory_204': { id: 'accessory_204', displayName: 'accessory_204', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_204.png`, canvasSize: { width: 174, height: 173 } },
  'accessory_205': { id: 'accessory_205', displayName: 'accessory_205', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_205.png`, canvasSize: { width: 127, height: 201 } },
  'accessory_206': { id: 'accessory_206', displayName: 'accessory_206', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_206.png`, canvasSize: { width: 165, height: 181 } },
  'accessory_207': { id: 'accessory_207', displayName: 'accessory_207', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_207.png`, canvasSize: { width: 177, height: 165 } },
  'accessory_208': { id: 'accessory_208', displayName: 'accessory_208', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_208.png`, canvasSize: { width: 162, height: 155 } },
  'accessory_209': { id: 'accessory_209', displayName: 'accessory_209', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_209.png`, canvasSize: { width: 122, height: 185 } },
  'accessory_210': { id: 'accessory_210', displayName: 'accessory_210', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_210.png`, canvasSize: { width: 172, height: 160 } },
  'accessory_211': { id: 'accessory_211', displayName: 'accessory_211', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_211.png`, canvasSize: { width: 110, height: 216 } },
  'accessory_212': { id: 'accessory_212', displayName: 'accessory_212', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_212.png`, canvasSize: { width: 140, height: 180 } },
  'accessory_213': { id: 'accessory_213', displayName: 'accessory_213', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_213.png`, canvasSize: { width: 174, height: 203 } },
  'accessory_214': { id: 'accessory_214', displayName: 'accessory_214', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_214.png`, canvasSize: { width: 177, height: 151 } },
  'accessory_215': { id: 'accessory_215', displayName: 'accessory_215', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_215.png`, canvasSize: { width: 146, height: 172 } },
  'accessory_216': { id: 'accessory_216', displayName: 'accessory_216', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_216.png`, canvasSize: { width: 113, height: 186 } },
  'accessory_217': { id: 'accessory_217', displayName: 'accessory_217', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_217.png`, canvasSize: { width: 130, height: 184 } },
  'accessory_218': { id: 'accessory_218', displayName: 'accessory_218', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_218.png`, canvasSize: { width: 192, height: 173 } },
  'accessory_219': { id: 'accessory_219', displayName: 'accessory_219', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_219.png`, canvasSize: { width: 113, height: 180 } },
  'accessory_220': { id: 'accessory_220', displayName: 'accessory_220', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_220.png`, canvasSize: { width: 182, height: 170 } },
  'accessory_221': { id: 'accessory_221', displayName: 'accessory_221', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_221.png`, canvasSize: { width: 137, height: 201 } },
  'accessory_222': { id: 'accessory_222', displayName: 'accessory_222', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_222.png`, canvasSize: { width: 141, height: 183 } },
  'accessory_223': { id: 'accessory_223', displayName: 'accessory_223', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_223.png`, canvasSize: { width: 169, height: 159 } },
  'accessory_224': { id: 'accessory_224', displayName: 'accessory_224', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_224.png`, canvasSize: { width: 166, height: 126 } },
  'accessory_225': { id: 'accessory_225', displayName: 'accessory_225', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_225.png`, canvasSize: { width: 130, height: 171 } },
  'accessory_226': { id: 'accessory_226', displayName: 'accessory_226', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_226.png`, canvasSize: { width: 126, height: 168 } },
  'accessory_227': { id: 'accessory_227', displayName: 'accessory_227', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_227.png`, canvasSize: { width: 179, height: 198 } },
  'accessory_228': { id: 'accessory_228', displayName: 'accessory_228', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_228.png`, canvasSize: { width: 128, height: 203 } },
  'accessory_229': { id: 'accessory_229', displayName: 'accessory_229', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_229.png`, canvasSize: { width: 143, height: 180 } },
  'accessory_230': { id: 'accessory_230', displayName: 'accessory_230', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_230.png`, canvasSize: { width: 181, height: 161 } },
  'accessory_231': { id: 'accessory_231', displayName: 'accessory_231', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_231.png`, canvasSize: { width: 148, height: 169 } },
  'accessory_232': { id: 'accessory_232', displayName: 'accessory_232', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_232.png`, canvasSize: { width: 94, height: 185 } },
  'accessory_233': { id: 'accessory_233', displayName: 'accessory_233', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_233.png`, canvasSize: { width: 154, height: 180 } },
  'accessory_234': { id: 'accessory_234', displayName: 'accessory_234', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_234.png`, canvasSize: { width: 145, height: 178 } },
  'accessory_235': { id: 'accessory_235', displayName: 'accessory_235', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_235.png`, canvasSize: { width: 172, height: 143 } },
  'accessory_236': { id: 'accessory_236', displayName: 'accessory_236', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_236.png`, canvasSize: { width: 144, height: 201 } },
  'accessory_237': { id: 'accessory_237', displayName: 'accessory_237', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_237.png`, canvasSize: { width: 152, height: 174 } },
  'accessory_238': { id: 'accessory_238', displayName: 'accessory_238', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_238.png`, canvasSize: { width: 170, height: 184 } },
  'accessory_239': { id: 'accessory_239', displayName: 'accessory_239', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_239.png`, canvasSize: { width: 128, height: 186 } },
  'accessory_240': { id: 'accessory_240', displayName: 'accessory_240', slot: 'unknown', src: `${DECO_BASE}/unknown/accessory_240.png`, canvasSize: { width: 172, height: 187 } },
}
